# Generated by Django 5.2.7 on 2025-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='user_pictures/default.png', upload_to='user_pictures'),
        ),
    ]
