# Generated by Django 5.2.7 on 2025-12-07 12:54

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('standard', 'Standard Delivery (5-7 days)'), ('express', 'Express Delivery (2-3 days)'), ('overnight', 'Overnight Delivery (Next day)'), ('pickup', 'In-Store Pickup')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_notes', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('signature_required', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_deli_status_460d58_idx'), models.Index(fields=['tracking_number'], name='orders_deli_trackin_1c1712_idx'), models.Index(fields=['order'], name='orders_deli_order_i_8826a8_idx')],
            },
        ),
    ]
